In [35]:
import numpy as np

class ConvNeuron():
    def __init__(self,kernel_size,padding_size):
        self.kernel_size=kernel_size # kernel_size: n -> means n*n 
        self.padding_size=padding_size # padding_size:n , image width:w , image height:h -> w=w+2n,h=h+2n
        
        self.weight_initialize() # initalize weights and bias
        
    def weight_initialize(self):
        self.Kernel=np.random.random([self.kernel_size,self.kernel_size])# Kernel: [n,n] size np array,randomly initialize
        self.bias=np.random.random(1) # bias : scalar 
        
    def Padding(self,input_data):
        H,W=input_data.shape # H as height of image, W as width of image
        x=input_data 
        for i in range(self.padding_size):  #from 0 to self.padding_size
            x=np.insert(x,W+i*2,0,axis=1)  # np.insert(array,index_,valuse,axis_dimension): add 0 to column W+i
            x=np.insert(x,0,0,axis=1)      # as above
            
        
        for j in range(self.padding_size): #from 0 to self.padding_size
            x=np.insert(x,H+j*2,0,axis=0) # add 0 array to row H+j
            x=np.insert(x,0,0,axis=0)     # add 0 array to row 0
            
        
        return x
        
        
        
    def Forward(self,input_data): 
        #forward operation of convolutional neuron
        L,W=input_data.shape  # get shap of data: L :length(height), W:width
        k=self.kernel_size    #kernel size
        output=np.zeros([L-k+1,W-k+1])    #declare output size array
        
        #operation of convolution~~~~~~~
        for i in range(L-k+1):            
            for j in range(W-k+1):
                for ii in range(k):
                    for jj in range(k):
                        output[i,j]+=input_data[i+ii,j+jj]*self.Kernel[ii,jj]
        output+=self.bias
        #end of convolution--------
        return output

    def __call__(self, input_data):
        '''
        it is an useful internal function to make coding simpler.
        e.g.
        no __call__ :
        
        a=ConvNeuron(5,5)
        x=a.operationA(input)
        x=a.operationB(x)
        x=a.operationC(x)
        
        with __call__ :
        first define __call__,
        
        def __call__(self,x):
            x=self.operationA(x)
            x=self.operationB(x)
            x=self.operationC(x)
            return x
        
        a=ConvNeuron(5,5)
        x=a(input)       
        '''
        #return self.Forward(input_data)
        x=self.Padding(input_data)
        x=self.Forward(x)
        return x
    
    
    
        

a=ConvNeuron(5,2) # define a as ConvNeuron object, kernel_size=5,padding_size=2

inp=np.random.random([10,10])# given a random arrray of size[10,10]

x=a(inp) # calculate
print(x.shape)
print(x)

(10, 10)
[[2.65537882 3.42546171 3.77591198 3.70725107 3.89162438 3.7888874
  4.39012364 4.16923332 3.59167933 2.5952709 ]
 [3.73681637 4.70641257 5.23444373 4.59964302 4.24766304 3.85026176
  4.450518   5.13482345 3.78904876 3.02245853]
 [4.14533139 5.40489634 5.59604104 5.25043062 4.94519388 4.73189366
  5.06763297 5.5300458  5.22172631 2.99275921]
 [4.17963142 5.44325722 5.25376551 5.42728744 4.53075729 4.47697284
  4.91773733 5.35541108 4.74239333 3.3296519 ]
 [3.62872993 5.67617691 5.82769576 4.93257271 5.14628887 4.9738969
  4.7171712  5.81421659 4.82974886 3.25459803]
 [3.81587423 5.66272868 5.51275882 5.22715726 4.91029069 5.71695483
  5.1542929  5.84978213 5.22959544 3.33890499]
 [3.8643243  6.10904203 5.88869143 5.58397529 5.82049046 4.44135227
  5.14569776 5.34427241 4.66888767 3.3168134 ]
 [3.534619   5.95833908 5.3700322  5.13095076 5.28315974 4.92038876
  5.32500407 5.21051303 4.33587111 3.04247391]
 [3.13390188 4.51220785 4.10892415 3.75695677 4.18852408 3.753443
  3.710

In [6]:
class PoolingNeuron():
    def __init__(self):
        self.weight_initialize()
        
    def weight_initialize(self):
        self.bias=np.random.random(1)# only bias here
        
    def Forward(self,input_data):
        L,W=input_data.shape   #get shape of data L:length, W:width
        a=int(L/2)
        b=int(W/2)
        output=np.zeros([a,b]) # create zero array of size[a,b]
        
        #pooling operation----
        for i in range(a):
            for j in range(b):
                output[i,j]=np.mean([input_data[i*2,j*2:j*2+1],input_data[i*2+1,j*2:j*2+1]])
        output+=self.bias
        #end of pooling operation----
        
        return output
    
    def __call__(self,input_data):
        return self.Forward(input_data)


b=PoolingNeuron()
x=np.random.random([6,6])
print(x)
y=b(x)
print(y)

[[0.23276065 0.43400821 0.71361867 0.79493717 0.69097136 0.79365414]
 [0.72761466 0.86694873 0.74227009 0.32699515 0.2975437  0.62804713]
 [0.29613181 0.87993934 0.08944349 0.74431119 0.48240537 0.05974742]
 [0.55908283 0.14290167 0.93202691 0.3519922  0.64160045 0.8586509 ]
 [0.75636621 0.90755453 0.91821949 0.76107279 0.92749188 0.48925822]
 [0.63052778 0.91087488 0.82120979 0.64768426 0.80250845 0.45956453]]
[[1.15302275 1.40077947 1.16709262]
 [1.10044241 1.18357029 1.234838  ]
 [1.36628208 1.54254973 1.53783525]]


In [9]:
class ScalarNeuron():
    def __init__(self,input_size):
        #multiple scalar inputs,or see them as plenty of [1x1] array is also ok.
        self.input_size=input_size #define input size
        self.weight_initialize()  
        
    def weight_initialize(self):
        self.weights=np.random.random([self.input_size]) # same as input size, or how many scalar inputs
        self.bias=np.random.random(1) # only 1 bias
    
    def Forward(self,input_data):        
        y=np.multiply(input_data,self.weights) #elementwise multiply output size is [self.input_size]
        y=np.sum(y)+self.bias # output is scalar.
        return y
    
    def __call__(self,input_data):
        return self.Forward(input_data)

Size=10    
L=ScalarNeuron(Size)
x=np.random.random([Size])
print(x)
y=L(x)
print(y)
    

[0.78775468 0.18163111 0.44649686 0.0734731  0.15759268 0.17889096
 0.21946992 0.90734053 0.83754784 0.46244123]
[2.29948541]
